#Open Weather conf
open.weather.url.coords=https://api.openweathermap.org/data/2.5/weather?lat={lat}&lon={lon}&appid={appid}&units={units}
open.weather.url.city=https://api.openweathermap.org/data/2.5/weather?q={cityName}&appid={appid}&units={units}

#Spotify conf
spotify.url=https://api.spotify.com/v1/search?q=genre:{genre}&type=track&limit={limit}&offset={offset}
spotify.request.accesstoken.url=https://accounts.spotify.com/api/token
spotify.limit=20
spotify.app.name=spotify

#AWS Secret manager conf
spring.config.import=aws-secretsmanager:dev/tracks-by-weather-secrets

#DynamoDB conf
dynamodb.accesstoken.table.name=AccessToken

#PostgreSQL
spring.datasource.url=jdbc:postgresql://tracksbyweather.cr02ey0ks3oj.us-east-1.rds.amazonaws.com:5432/tracksbyweather
spring.datasource.username=tracksbyweather
spring.datasource.password=${BD_PASS}